In [1]:
def fib(n , c={0:0,1:1}):
    if n in c:
          return c[n]
    c[n]= fib(n-1)+fib(n-2)
    return c[n]
print(fib(100))

354224848179261915075


In [25]:
n = int(input())
for i in range(2, n):
    if n % i == 0:
        print(i)
        n = n/i
else: n = n 

        
            

2
3
4
8
643


In [39]:
def triangle(size,symb):
    i = 1
    while (i < size/2):
        print(i+symb)
    if i == size/2:
        print(i+symb)
    while (i >= 1):
        print(i+symb)



In [45]:
size = int(input())
symb = str(input())
def triangle(size,symb,cur = 1):
    if size == 0:
        return
    print(min(cur,size)*symb)
    triangle(size-1,symb,cur+1)


In [4]:
import numpy as np
def mnk(x,y):
    x = np.array(x)
    y = np.array(y)
    a = ((x*y).mean() - x.mean()*y.mean()) / x.mean()**2
    b = y.mean() - a*x.mean()
    return a,b
x = [1,2,3,4,5]
y = [2,3,5,6,7]
print(mnk(x,y))


(np.float64(0.28888888888888886), np.float64(3.733333333333333))


In [13]:
import numpy as np
def spiral(n,m):
    A = np.zeros((n,m))
    a , i , j = 1 , 0 , 0
    while (a < m*n):
            while (j+1 < m and A[i][j+1]==0 ):
                A[i][j] = a
                a += 1
                j += 1
            while(i+1 < n and A[i+1][j]==0 ):   
                A[i][j] = a
                a += 1
                i += 1 
            while (j > 0 and A[i][j-1]==0 ):
                A[i][j] = a
                a += 1
                j -= 1
            while(i > 0 and A[i-1][j]==0 ):   
                A[i][j] = a
                a += 1
                i -= 1 
    A[i][j] = a
    return A
print(spiral(6,7))       
            
            
    

[[ 1.  2.  3.  4.  5.  6.  7.]
 [22. 23. 24. 25. 26. 27.  8.]
 [21. 36. 37. 38. 39. 28.  9.]
 [20. 35. 42. 41. 40. 29. 10.]
 [19. 34. 33. 32. 31. 30. 11.]
 [18. 17. 16. 15. 14. 13. 12.]]


In [6]:
import numpy as np
n = int(input())
m = int(input())
d = []
for i in range(n):
   d.append([input() for _ in range(m)])

for i in range(n):
   for j in range(m):
      print(d[i][j], end=' ')
   print()    




1 2 
3 4 
